Veterinaria/Models/Pagina.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagina
    {
        public int Id_Pagina { get; set; }
        public string Quienes { get; set; }
        public string Servicios { get; set; }
        public string Visitanos { get; set; }
        public string Inicio { get; set; }
    }
}

Veterinaria/Controllers/PaginasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Veterinaria.Models;

namespace Veterinaria.Controllers
{
    public class PaginasController : Controller
    {
        private VeterinariaContainer db = new VeterinariaContainer();

        // GET: Paginas
        public ActionResult Index()
        {
            return View(db.PaginaSet.ToList());
        }

        // GET: Paginas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pagina pagina = db.PaginaSet.Find(id);
            if (pagina == null)
            {
                return HttpNotFound();
            }
            return View(pagina);
        }

        // GET: Paginas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Paginas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Pagina,Quienes,Servicios,Visitanos,Inicio")] Pagina pagina)
        {
            if (ModelState.IsValid)
            {
                db.PaginaSet.Add(pagina);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pagina);
        }

        // GET: Paginas/Edit/5
        public ActionResult Edit(string id)
        {
            ViewBag.Content = id;
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pagina pagina = db.PaginaSet.FirstOrDefault();
            if (pagina == null)
            {
                return HttpNotFound();
            }
            return View(pagina);
        }

        // POST: Paginas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pagina pagina)
        {
            if (ModelState.IsValid)
            {
                var page = db.PaginaSet.FirstOrDefault();
                page.Quienes = !string.IsNullOrEmpty(pagina.Quienes) ? pagina.Quienes : page.Quienes;
                page.Servicios = !string.IsNullOrEmpty(pagina.Servicios) ? pagina.Servicios : page.Servicios;
                page.Visitanos = !string.IsNullOrEmpty(pagina.Visitanos) ? pagina.Visitanos : page.Visitanos;
                page.Inicio = !string.IsNullOrEmpty(pagina.Inicio) ? pagina.Inicio : page.Inicio;

                //db.Entry(pagina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pagina);
        }

        // GET: Paginas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pagina pagina = db.PaginaSet.Find(id);
            if (pagina == null)
            {
                return HttpNotFound();
            }
            return View(pagina);
        }

        // POST: Paginas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pagina pagina = db.PaginaSet.Find(id);
            db.PaginaSet.Remove(pagina);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Veterinaria/Views/Paginas/Create.cshtml
@model Veterinaria.Models.Pagina

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pagina</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Quienes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Quienes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quienes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Servicios, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Servicios, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Servicios, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Visitanos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Visitanos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Visitanos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Inicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Inicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Inicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atras", "Index", null, htmlAttributes: new { @class = "btn btn-Sucess" })
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Veterinaria/Views/Paginas/Delete.cshtml
@model Veterinaria.Models.Pagina

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pagina</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quienes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quienes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Servicios)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Servicios)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visitanos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visitanos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inicio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Atras", "Index")
        </div>
    }
</div>

Veterinaria/Views/Paginas/Details.cshtml
@model Veterinaria.Models.Pagina

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pagina</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quienes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quienes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Servicios)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Servicios)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visitanos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visitanos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inicio)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id_Pagina }) |
    @Html.ActionLink("Atras", "Index")
</p>

Veterinaria/Views/Paginas/Edit.cshtml
@model Veterinaria.Models.Pagina

@{
    ViewBag.Title = "Editar";
  
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pagina</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Pagina)

        @if (ViewBag.Content == "Quienes")
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Quienes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Quienes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quienes, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        
        @if (ViewBag.Content == "Servicios")
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Servicios, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Servicios, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Servicios, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        
        @if (ViewBag.Content == "Visitanos")
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Visitanos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Visitanos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Visitanos, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        @if (ViewBag.Content == "Inicio")
        { 
            <div class="form-group">
                @Html.LabelFor(model => model.Inicio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Inicio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Inicio, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atras", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Veterinaria/Views/Paginas/Index.cshtml
@model IEnumerable<Veterinaria.Models.Pagina>

@{
    ViewBag.Title = "Index";
}

<h2>Paginas</h2>


<table class="table">
    @*<tr>
        <th>
            @Html.DisplayNameFor(model => model.Quienes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Servicios)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Visitanos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Inicio)
        </th>
        <th></th>
    </tr>*@

    @foreach (var item in Model)
    {
        <tbody style="border-color:gray;border-width:4px;margin-bottom:10px;">
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.Quienes)</b>
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = "Quienes" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Raw(item.Quienes)
                </td>
                @*<td>
                @Html.Raw(item.Servicios)
            </td>
            <td>
                @Html.Raw(item.Visitanos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inicio)
            </td>

            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id_Pagina }) |
                @Html.ActionLink("Consultar", "Details", new { id = item.Id_Pagina }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id_Pagina }) |
                @Html.ActionLink("Agregar Pagina", "Create", "Paginas", new { propietarioId = item.Id_Pagina }, null) |
                @Html.ActionLink("Ver Paginas", "Details", "Paginas", new { id = item.Id_Pagina }, null)
            </td>*@
            </tr>
        </tbody>
        <tbody style="border-color:gray;border-width:2px;margin-bottom:5px;">
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.Servicios)</b>
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = "Servicios" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Raw(item.Servicios)
                </td>
            </tr>
        </tbody>
        <tbody style="border-color:gray;border-width:4px;margin-bottom:10px;">
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.Visitanos)</b>
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = "Visitanos" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Raw(item.Visitanos)
                </td>
            </tr>
        </tbody>
        <tbody style="border-color:gray;border-width:4px;margin-bottom:10px;">
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.Inicio)</b>
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = "Inicio" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.Raw(item.Inicio)
                </td>
            </tr>
        </tbody>
    }

</table>