Veterinaria/Models/Mascota.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public int Id_Mascota { get; set; }
        public string Nombre { get; set; }
        public string Edad { get; set; }
        public string Color { get; set; }
        public string Raza { get; set; }
        public string Especie { get; set; }
        public string Peso { get; set; }
        public int Id_Propietario { get; set; }
    }
}

Veterinaria/Controllers/Historia_ClinicaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Veterinaria.Models;

namespace Veterinaria.Controllers
{
    public class Historia_ClinicaController : Controller
    {
        private VeterinariaContainer db = new VeterinariaContainer();

        // GET: Historia_Clinica
        public ActionResult Index(int id)
        {
            ViewBag.Mascota = db.MascotaSet.SingleOrDefault(x => x.Id_Mascota == id);
            return View(db.Historia_ClinicaSet.Where(x => x.Id_Mascota == id).ToList());
        }

        // GET: Historia_Clinica/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Historia_Clinica historia_Clinica = db.Historia_ClinicaSet.Find(id);
            if (historia_Clinica == null)
            {
                return HttpNotFound();
            }
            return View(historia_Clinica);
        }

        // GET: Historia_Clinica/Create
        public ActionResult Create(int id)
        {
            ViewBag.Mascota = db.MascotaSet.SingleOrDefault(x => x.Id_Mascota == id);
            return View(new Historia_Clinica
            {
                Id_Mascota = id
            });
        }

        // POST: Historia_Clinica/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Historia_Clinica historia_Clinica)
        {
            if (ModelState.IsValid)
            {
                db.Historia_ClinicaSet.Add(historia_Clinica);
                db.SaveChanges();
                return RedirectToAction("Index/" + historia_Clinica.Id_Mascota);
            }

            return View(historia_Clinica);
        }

        // GET: Historia_Clinica/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Historia_Clinica historia_Clinica = db.Historia_ClinicaSet.Find(id);
            if (historia_Clinica == null)
            {
                return HttpNotFound();
            }
            return View(historia_Clinica);
        }

        // POST: Historia_Clinica/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Historia_Clinica,Diagnostico,Sintomas,Id_Mascota")] Historia_Clinica historia_Clinica)
        {
            if (ModelState.IsValid)
            {
                db.Entry(historia_Clinica).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(historia_Clinica);
        }

        // GET: Historia_Clinica/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Historia_Clinica historia_Clinica = db.Historia_ClinicaSet.Find(id);
            if (historia_Clinica == null)
            {
                return HttpNotFound();
            }
            return View(historia_Clinica);
        }

        // POST: Historia_Clinica/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Historia_Clinica historia_Clinica = db.Historia_ClinicaSet.Find(id);
            db.Historia_ClinicaSet.Remove(historia_Clinica);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Veterinaria/Controllers/MascotasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Veterinaria.Models;

namespace Veterinaria.Controllers
{
    public class MascotasController : Controller
    {
        private VeterinariaContainer db = new VeterinariaContainer();

        public ActionResult ByPropietario(int id)
        {
            ViewBag.Propietario = db.PropietarioSet.SingleOrDefault(x => x.Id_Propietario == id);
            return View(db.MascotaSet.Where(x => x.Id_Propietario == id).ToList());
        }

        // GET: Mascotas
        public ActionResult Index()
        {
            return View(db.MascotaSet.ToList());
        }

        // GET: Mascotas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mascota mascota = db.MascotaSet.Find(id);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            return View(mascota);
        }

        // GET: Mascotas/Create
        public ActionResult Create(int propietarioId)
        {
            ViewBag.Propietario = db.PropietarioSet.SingleOrDefault(x => x.Id_Propietario == propietarioId);
            return View(new Mascota
            {
                Id_Propietario = propietarioId
            });
        }

        // POST: Mascotas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                db.MascotaSet.Add(mascota);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mascota);
        }

        // GET: Mascotas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mascota mascota = db.MascotaSet.Find(id);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            return View(mascota);
        }

        // POST: Mascotas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mascota).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mascota);
        }

        // GET: Mascotas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mascota mascota = db.MascotaSet.Find(id);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            return View(mascota);
        }

        // POST: Mascotas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Mascota mascota = db.MascotaSet.Find(id);
            db.MascotaSet.Remove(mascota);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Veterinaria/Views/Mascotas/ByPropietario.cshtml
@model IEnumerable<Veterinaria.Models.Mascota>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de mascotas</h2>

<div>
    <h4>Propietario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <b style="text-transform:uppercase;">@ViewBag.Propietario.Nombre</b>
        </dd>
    </dl>
</div>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Raza)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Especie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raza)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Peso)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id_Mascota }) |
                @Html.ActionLink("Consultar", "Details", new { id = item.Id_Mascota }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id_Mascota }) |
                @Html.ActionLink("Ver historial", "Index", "Historia_Clinica", new { id = item.Id_Mascota }, null)
            </td>
        </tr>
    }

</table>

Veterinaria/Views/Mascotas/Create.cshtml
@model Veterinaria.Models.Mascota

@{
    ViewBag.Title = "Create";
}

<h2>Crear Mascota</h2>

<div>
    <h4>Propietario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <b style="text-transform:uppercase;">@ViewBag.Propietario.Nombre</b>
        </dd>
    </dl>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id_Propietario)
    
    <div class="form-horizontal">
        <h4>Mascota</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Raza, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Raza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Especie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Especie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Especie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atras", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Veterinaria/Views/Mascotas/Delete.cshtml
@model Veterinaria.Models.Mascota

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mascota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raza)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Raza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Atras", "Index")
        </div>
    }
</div>

Veterinaria/Views/Mascotas/Details.cshtml
@model Veterinaria.Models.Mascota

@{
    ViewBag.Title = "Details";
}

<h2>Consultar</h2>

<div>
    <h4>Mascota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raza)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Raza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id_Mascota }) |
    @Html.ActionLink("Atras", "Index")
</p>

Veterinaria/Views/Mascotas/Edit.cshtml
@model Veterinaria.Models.Mascota

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Mascota</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mascota</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Mascota)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Raza, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Raza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Especie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Especie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Especie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atras", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Veterinaria/Views/Mascotas/Index.cshtml
@model IEnumerable<Veterinaria.Models.Mascota>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de mascotas</h2>

<p>
    @*@Html.ActionLink("Nueva Mascota", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Raza)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Especie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Raza)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Especie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Peso)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id_Mascota }) |
            @Html.ActionLink("Consultar", "Details", new { id = item.Id_Mascota }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id_Mascota }) |
            @Html.ActionLink("Ver historial", "Index", "Historia_Clinica", new { id = item.Id_Mascota }, null)

        </td>
    </tr>
}

</table>